In [ ]:
from PIL import Image 
import numpy as np
import math

In [ ]:
im = Image.open("../static/lena512.pbm")
for pixel in list(im.getdata()):
    print(pixel)

In [ ]:
from scipy.misc import imread
# Convert an image to 2D array 
img_array = imread("../static/lena512.pbm")
print(img_array)

# Scaling Algorithms

In [ ]:
# Modified nearest neighbor
def nearestNeighbor(img_matrix, w2, h2):
    w1 = len(img_matrix[0])
    h1 = len(img_matrix)
    x_ratio = w1 / float(w2)
    y_ratio = h1 / float(h2)
    new_matrix = np.zeros((h2, w2))
    for i in range(h2):
        for j in range(w2):
            px = math.floor(j * x_ratio)
            py = math.floor(i * y_ratio)
            new_matrix[i][j] = img_matrix[py][px]
    return new_matrix

Image.fromarray(nearestNeighbor(img_array, 300, 350).astype('uint8')).save("../static/new_images/re_300_350.pbm")
Image.fromarray(nearestNeighbor(img_array, 500, 570).astype('uint8')).save("../static/new_images/re_500_570.pbm")

In [ ]:
def linearX(img_matrix, w2, h2):
    w1 = len(img_matrix[0])
    h1 = len(img_matrix)
    x_ratio = float(w1 - 1) / w2
    y_ratio = float(h1) / h2
    new_matrix = np.zeros((h2, w2))
    for i in range(h2):
        for j in range(w2):
            x = int(x_ratio * j)
            y = int(y_ratio * i)
            A = img_matrix[y][x]
            B = img_matrix[y][x+1]
            x_diff = (x_ratio * j) - x
            new_pixel_value = int(A * (1 - x_diff) + B * x_diff)
            new_matrix[i][j] = new_pixel_value
    return new_matrix

Image.fromarray(linearx(img_array, 400, 400).astype('uint8')).save("../static/new_images/400_400.pbm")
Image.fromarray(linearx(img_array, 400, 350).astype('uint8')).save("../static/new_images/400_350.pbm")
Image.fromarray(linearx(img_array, 600, 615).astype('uint8')).save("../static/new_images/600_615.pbm")
Image.fromarray(linearx(img_array, 600, 600).astype('uint8')).save("../static/new_images/600_600.pbm")

In [ ]:
def linearY(img_matrix, w2, h2):
    w1 = len(img_matrix[0])
    h1 = len(img_matrix)
    x_ratio = float(w1) / w2
    y_ratio = float(h1 - 1) / h2
    new_matrix = np.zeros((h2, w2))
    for i in range(h2):
        for j in range(w2):
            x = int(x_ratio * j)
            y = int(y_ratio * i)
            A = img_matrix[y][x]
            C = img_matrix[y+1][x]
            y_diff = (y_ratio * i) - y
            new_pixel_value = int(A * (1 - y_diff) + C * y_diff)
            new_matrix[i][j] = new_pixel_value
    return new_matrix

Image.fromarray(linearY(img_array, 400, 400).astype('uint8')).save("../static/new_images/400_400.pbm")
Image.fromarray(linearY(img_array, 400, 350).astype('uint8')).save("../static/new_images/400_350.pbm")
Image.fromarray(linearY(img_array, 600, 615).astype('uint8')).save("../static/new_images/600_615.pbm")
Image.fromarray(linearY(img_array, 600, 600).astype('uint8')).save("../static/new_images/600_600.pbm")

In [ ]:
# Modified bilinear
def bilinear(img_matrix, w2, h2):
    w1 = len(img_matrix[0])
    h1 = len(img_matrix)
    x_ratio = float(w1 - 1) / w2
    y_ratio = float(h1 - 1) / h2
    new_matrix = np.zeros((h2, w2))
    for i in range(h2):
        for j in range(w2):
            x = int(x_ratio * j)
            y = int(y_ratio * i)
            A = img_matrix[y][x]
            B = img_matrix[y][x+1]
            C = img_matrix[y+1][x]
            D = img_matrix[y+1][x+1]
            x_diff = (x_ratio * j) - x
            y_diff = (y_ratio * i) - y
            new_pixel_val = int(A * (1 - x_diff) * (1 - y_diff) 
                      + B * (x_diff) * (1 - y_diff)
                      + C * (y_diff) * (1 - x_diff)
                      + D * (x_diff * y_diff))
            new_matrix[i][j] = new_pixel_val
    return new_matrix

Image.fromarray(bilinear(img_array, 350, 350).astype('uint8')).save("../static/new_images/re_350_350.pbm")
Image.fromarray(bilinear(img_array, 220, 220).astype('uint8')).save("../static/new_images/re_220_220.pbm")
Image.fromarray(bilinear(img_array, 500, 600).astype('uint8')).save("../static/new_images/re_500_600.pbm")

# Gray Level 

In [53]:
# Gray level convertor function
def gray_level_convertor(img_array, ori_gray_level, new_gray_level):
    ori_pixel_range = 2 ** ori_gray_level
    new_pixel_range = 2 ** new_gray_level
    ratio = float(new_pixel_range) / float(ori_pixel_range)
    new_img_array = np.copy(img_array)
    for row in range(len(img_array)):
        for col in range(len(img_array[row])):
            new_img_array[row][col] = int(img_array[row][col] * ratio) * (256 / (2 ** new_gray_level))
    return new_img_array

print(gray_level_convertor(img_array, 8, 7))

[[162 162 162 ... 170 154 128]
 [162 162 162 ... 170 154 128]
 [162 162 162 ... 170 154 128]
 ...
 [ 42  42  50 ... 104 100  98]
 [ 44  44  54 ... 104 104 108]
 [ 44  44  54 ... 104 104 108]]


In [55]:
Image.fromarray(gray_level_convertor(img_array, 8, 7)).save("../static/new_images/8_2_7.pbm")
Image.fromarray(gray_level_convertor(img_array, 8, 6)).save("../static/new_images/8_2_6.pbm")
Image.fromarray(gray_level_convertor(img_array, 8, 5)).save("../static/new_images/8_2_5.pbm")
Image.fromarray(gray_level_convertor(img_array, 8, 4)).save("../static/new_images/8_2_4.pbm")
Image.fromarray(gray_level_convertor(img_array, 8, 3)).save("../static/new_images/8_2_3.pbm")
Image.fromarray(gray_level_convertor(img_array, 8, 2)).save("../static/new_images/8_2_2.pbm")
Image.fromarray(gray_level_convertor(img_array, 8, 1)).save("../static/new_images/8_2_1.pbm")

In [ ]:
import numpy as np
from PIL import Image 
# Plot a grayscale image with a 2D array 
img = Image.fromarray(img_array)
img.save("../new_images/new_img.pbm")

In [ ]:
import matplotlib.pyplot as plt
import matplotlib.image as mpimg
# Display the image
img = mpimg.imread("../new_images/new_img.pbm")
imgplot = plt.imshow(img)
plt.show()

## Temp

In [ ]:
import math
# Scaling function
def nearestNeighbor(img_array, w2, h2):
    one_dimension_img_array = img_array.flatten()
    w1 = len(img_array[0])
    h1 = len(img_array)
    x_ratio = w1 / float(w2)
    y_ratio = h1 / float(h2)
    px, py = 0, 0
    new_array = np.arange(w2 * h2)
    for i in range(h2):
        for j in range(w2):
            px = math.floor(j * x_ratio)
            py = math.floor(i * y_ratio)
            new_array[(i * w2) + j] = one_dimension_img_array[int((py * w1) + px)]
    return new_array.reshape(w2, h2)

Image.fromarray(nearestNeighbor(img_array, 300, 350).astype('uint8')).save("../new_images/re_300_350.pbm")
Image.fromarray(nearestNeighbor(img_array, 500, 570).astype('uint8')).save("../new_images/re_500_570.pbm")

In [ ]:
# Scaling function using bilinear method
def bilinear(img_array, w2, h2):
    one_dimension_img_array = img_array.flatten()
    w1 = len(img_array[0])
    h1 = len(img_array)
    x_ratio = float(w1 - 1) / w2
    y_ratio = float(h1 - 1) / h2
    offset = 0
    new_array = np.arange(w2 * h2)
    for i in range(h2):
        for j in range(w2):
            x = int(x_ratio * j)
            y = int(y_ratio * i)
            x_diff = (x_ratio * j) - x
            y_diff = (y_ratio * i) - y
            index = y * w1 + x
            A = one_dimension_img_array[index]
            B = one_dimension_img_array[index + 1]
            C = one_dimension_img_array[index + w1]
            D = one_dimension_img_array[index + w1 + 1]
            gray = int(A * (1 - x_diff) * (1 - y_diff) 
                      + B * (x_diff) * (1 - y_diff)
                      + C * (y_diff) * (1 - x_diff)
                      + D * (x_diff * y_diff))
            new_array[offset] = gray
            offset += 1
    return new_array.reshape(w2, h2)

Image.fromarray(bilinear(img_array, 350, 350).astype('uint8')).save("../static/new_images/re_350_350.pbm")
Image.fromarray(bilinear(img_array, 220, 220).astype('uint8')).save("../static/new_images/re_220_220.pbm")